### ISSUE TITLE
Proxy using splice

### ISSUE THREAD

**Issue by da-tai** [panjf2000/gnet#120]
Using ```net``` package, you can make a proxy using splice with io.Copy. Is that possible with gnet , or is there a faster way to doit with gnet?

```
go io.Copy(remote, conn)
io.Copy(conn, cs.remote)
```

https://man7.org/linux/man-pages/man2/splice.2.html

**Comment by panjf2000** [comment]
It is not currently supported in `gnet` yet.

**Comment by Swaggadan** [comment]
> It is not currently supported in `gnet` yet.

Any plans to do it soon or any other way to utilize something similar with gnet in the meantime.

**Comment by panjf2000** [comment]
> Any plans to do it soon or any other way to utilize something similar with gnet in the meantime.

This would be a long-term plan if I decide to do it because the current API design of `gnet` is not quite compatible with the `splice` syscall, you see, `gnet` doesn't expose any `file descriptor` to users, which make it hard to support `splice`.

I may add a new proxy feature to `gnet` in the future only for some scenarios like yours: building a proxy server on top of `gnet`.

As for the alternative, I'm afraid there is no such kind of thing in `gnet` for now.
