### ISSUE TITLE
Use a standard logging API

### ISSUE THREAD

**Issue by lookfirst** [panjf2000/gnet#160]
Right now, I have to write a wrapper around your logger.Logger, which is a paired down copy of the 'sugar' version of zap.

It sure would be nice to just pass in something that implements the standard golang Logger... then I don't have to maintain some wrapper.

**Comment by panjf2000** [comment]
Everyone has his own requirements, someone like you wants to print the logs into standard I/O while others want to print their logs into other storage like elasticsearch, kafka, etc. That's why I deliver the gnet logging interface for suiting all needs from different users.

You want to print your logs on standard I/O, he wants it in another way, I can't please everyone, so the simplest and most productive way is to make a canonical interface and everyone follows it.

**Comment by lookfirst** [comment]
My point is... use a standard interface instead of some random one from uber.

**Comment by panjf2000** [comment]
`zap` logger has more log levels like `debug`, `warn`, etc, which are missing from the go std logger.

**Comment by lookfirst** [comment]
The interface you export for me to implement, doesn't need those methods. All you need to export is Printf(). Your code can put whatever you want into there.
