### ISSUE TITLE
Max number of connections?

### ISSUE THREAD

**Issue by kpfaulkner** [panjf2000/gnet#197]
Hi

I'm only about day 3 into using gnet, but am wondering if there is a maximum number of connections that I need to configure? I'm attempting to get websockets working with gnet (combining the gobwas library). I attempt to hit the service with 1000 concurrent connections and the most I get is approx 600-ish...  (it's never the exact same). On the client side I can see that the Dial call is simply not getting a response back after request 600(ish).

I'm wondering if I'm just messing something up or if trying to combine gnet and long lived websockets is simply the wrong approach.  

Any advice on gnet and websockets?

Thanks

Ken

**Comment by ligser** [comment]
In my test runs, I handle 25000 concurrent WebSocket connections on the 2-core-4-Gb DigitalOcean droplet if every conn will send a ping every 2 seconds.
If I send pings every second I handle 20000 conns without noticeable delays (initial upgrade will take up to a minute but when conn become upgraded it can receive all needed pongs for each ping sent).
The bottleneck is mostly in CPU because overall memory usage is not higher than 300Mb for 25000 connections so I think a 4-core server can handle event more connections without code changes.
Without that frequent pings (if pings will be sent once per 5 minutes for example) I think gnet can handle much more but currently, I do not have that requirement to handle more than 20000 connections per server and I just do not run larger tests.

To achieve higher throughput try to embrace the gnet eventable nature. You should not do any heavy work in provided handlers: `OnMessage`, `OnOpened` etc. Try to do here only simple encoding/decoding. If you need to wait somewhere — try to offload that wait into goroutine (or to goroutines pool like the `ants`). Also, take care of synchronization. For example — you can call some of `gnet.Conn` methods only in events (`OnMessage`) during their execution — pay your attention to control that.
Pretty useful here can be something like pprof. It can show you if you have unexpected delays somewhere. Also, it can help when you will analyze concurrency.

**Comment by panjf2000** [comment]
I really appreciate your explanation here, thanks~
@ligser

**Comment by kpfaulkner** [comment]
Thanks for that rundown @ligser . Still trying to debug why I'm hitting that 600-ish limit. I *suspect* that the websocket upgrade is causing a bottleneck somewhere but still need to confirm. 

Currently I have my original (goroutine based websocket code) chugging away nicely with 4k concurrent sockets but really wanted to see if I could push gnet to up that load.

Will keep tinkering.

**Comment by kpfaulkner** [comment]
Sorry if these seem silly questions, still getting my head around gnet. But one thing I've noticed is that the upgrade reply isn't responding. I'm wondering if I need to do something special to get the ants event loop going properly. For example in the AsyncWrite function:

func (c *stdConn) AsyncWrite(buf []byte) (err error) {
	var encodedBuf []byte
	if encodedBuf, err = c.codec.Encode(c, buf); err == nil {
		c.loop.ch <- func() (err error) {
			if c.conn != nil {
				_, err = c.conn.Write(encodedBuf)
			}
			return
		}
	}
	return
}

I can see that buf has the correct websocket upgrade response, but if I put a breakpoint on the "if c.conn" line (ie the function put onto the channel) I can see it never gets executed. So the data is correct, the socket is correct but the function that was put onto the channel is never executed.  Am wondering if that is a symptom of anything obvious? (I'm still digging).

Thanks

Ken

**Comment by ligser** [comment]
Code where you call AsyncWrite can be really helpful here :) Please note that on windows if you use the AsyncWrite inside a `On*` events (like the `OnOpen`) - you should use goroutine because otherwise you probably have a deadlock here (it can put your write into a channel because channel is not buffered).

**Comment by kpfaulkner** [comment]
Hi

The code that's calling AsyncWrite is:

func (u Upgrader) Write(b []byte) (n int, err error) {

	u.WorkerPool.Submit(func() {
		u.GnetConn.AsyncWrite(b)
	})
	return len(b), nil
}

GnetConn is a gnet.Conn, and WorkerPool was created using :

	options := ants.Options{ExpiryDuration: time.Second * 1000, Nonblocking: true}
	antsPool, _ := ants.NewPool(1048576, ants.WithOptions(options))

Yes, the expiry duration is crazy big just for debugging. :)

Will try and break it down to a small reproduceable example later today/tomorrow.

Also, thanks for the heads up about Windows and using AsyncWrite... since yes, I'm on Windows.

**Comment by kpfaulkner** [comment]
Ok, sorted out my issue (was related to parsing websocket header... which was causing issues).
