### ISSUE TITLE
A server that also acts as a client

### ISSUE THREAD

**Issue by KevinRoebert** [panjf2000/gnet#345]
**Please fill out the following system information before opening an issue:**
 - OS (e.g. Ubuntu 18.04): MacOS Monterey 12.2.1
 - Go version (e.g. Go 1.13): go1.17.8 darwin/arm64
 - gnet version (e.g. v1.0.0): v2.0.1

**What is your question about gnet?**
Is there a way in gnet to start a UPD server and send a message to another server from the same FD without the server sending a message before.

**An example**: There is UDP server `A` and UDP server `B`. `A` and `B` have never communicated with each other before. `A` now wants to send a message to `B`.

How would I do something like this in gnet? Is it possible at all?

It is important that the port of UDP server `A` does not change when sending the message. So it is not possible to just create a new client, which then sends the message to `B`.

**Comment by panjf2000** [comment]
Couldn't you just create a UDP socket to server B in server A and bind that socket with the port you want?

**Comment by KevinRoebert** [comment]
> Couldn't you just create a UDP socket to server B in server A and bind that socket with the port you want?

Maybe, but how? `gnet.NewClient()` and `gnet.Client.Dial()` does not allow to bind to the socket of the UDP server `A`.

**Comment by panjf2000** [comment]
>  It is not an option to create a new socket.
Is there a way to send network messages without using sockets？

Besides, I don't think you are allowed to reuse an in-use port of an existing server as the source port of sender.

**Comment by HustCoderHu** [comment]
u want it working like this ?
ServerC (port m) -- msg --> ServerA (port n)  -- relay --> ServerB port(port p) -- rsp --> ServerA (port n)

u need to figure out a way send pkts to different peer from one local Conn object.

Does one udp Conn support customized peer addr on each asyncWrite ?

**Comment by civilizeddev** [comment]
@KevinRoebert 

I understand what you want. In fact, by using the builtin net package in Go to directly bind a UDP socket, one can read messages that are being listened to, or send them to another target. That might have allowed you to do what you want. However, the reason we use gnet is probably because it's more convenient than implementing directly with the builtin net package.

In gnet, internally, there is a file descriptor for a UDP socket bound to the server's port address in the event loop. In fact, it would be great if the gnet maintainer provided a convenient interface for this.

The workaround I found is as follows.

```
import (
	"net"
	"os"

	"github.com/panjf2000/gnet"
)

type server struct {
	*gnet.EventServer
	conn *net.PacketConn
}

func (s *server) OnInitComplete(svr gnet.Server) (action gnet.Action) {
	fd, err := svr.DupFd()
	if err != nil {
		log.Fatal(err)
	}
	file := os.NewFile(uintptr(fd), "udp")
	conn, err := net.FilePacketConn(file)
	if err != nil {
		log.Fatal(err)
	}
        // net.UDPConn, actually
	s.conn = &conn
	
	log.Printf("Listening %s://%s", svr.Addr.Network(), svr.Addr)
	return
}

...
```

And then it can be used elsewhere.

```
...

func (s *server) SendTo(p []byte, addr net.Addr) error {
	if _, err := (*d.conn).WriteTo(p, addr); err != nil {
		return err
	}
	return nil
}
```

In fact, because I am in a bit of a hurry, I had to make it work somehow. For the time being, I will use it this way, but as I mentioned before, I hope that gnet can make it more elegantly.

Thank you.
